CalendarApp/Controllers/MonthViewController.cs
using CalendarApp.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CalendarApp.Controllers
{
    public class MonthViewController : Controller
    {
            private ApplicationDbContext _context;

            public MonthViewController()
            {
                _context = new ApplicationDbContext();
            }

            protected override void Dispose(bool disposing)
            {
                _context.Dispose();
                base.Dispose(disposing);
            }

            // GET: MonthView
            public ActionResult Index(DateTime? month = null)
        {
            if (month == null)
            {
                month = DateTime.Today;
            }
            month = month.Value.AddDays(1 - month.Value.Day);

            var dates = new List<DateTime>();
            dates.Add(month.Value);

            for (var day = month.Value.AddDays(1); day.Month == month.Value.Month; day = day.AddDays(1))
            {
                dates.Add(day);
            }

            var dayOfWeek = month.Value.DayOfWeek;

            var weeks = new List<List<DayOfMonth>>
            {
                new List<DayOfMonth>(),
            };

            var currentWeek = 0;
            foreach (var date in dates)
            {
                var week = weeks[currentWeek];
                var tomorrow = date.AddDays(1);
                week.Add(new DayOfMonth
                {
                    Date = date,
                    Events = _context.NewEvents
                        .Where(e => e.TimeofEvent >= date && e.TimeofEvent < tomorrow)
                        .ToList()
                });

                if (date.DayOfWeek == DayOfWeek.Saturday)
                {
                    currentWeek = currentWeek + 1;
                    weeks.Add(new List<DayOfMonth>());
                }
            }

            return View(new MyMonthView
            {
                Month = month.Value,
                Weeks = weeks,
            });
        }

        [HttpPost]
        public ActionResult New(NewEvent newEvent)
        {
            //Create a new event, add it and save it to the database
            if (newEvent != null)
            {
                _context.NewEvents.Add(newEvent);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public ActionResult Single(int ID)
        {
            //Fetch the single event from the database
            NewEvent MyEvent;
            MyEvent = _context.NewEvents.SingleOrDefault(e => e.ID == ID);
            if(MyEvent == null)
            {
                return HttpNotFound();
            }
            return View(MyEvent);

        }

        public ActionResult Delete(int ID)
        {
            //Delete event from the database forever
            _context.NewEvents.Remove(_context.NewEvents.Find(ID));
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int ID)
        {
            NewEvent newEvent = _context.NewEvents.Find(ID);
            return View(newEvent);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Edit([Bind(Include = "ID, EventName, FirstName, TimeofEvent, Location, AdditionalNotes")] NewEvent newEvent)
        {
            //Edit an event from the database through the edit button
            if (newEvent != null)
            {
                _context.Entry(newEvent).State = EntityState.Modified;
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

CalendarApp/Views/MonthView/Edit.cshtml
@model CalendarApp.Models.NewEvent
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Event</h2>

@using (Html.BeginForm("Edit", "Jockey"))
{
<form>
    @Html.HiddenFor(n => n.ID)
    <div class="form-group">
        @Html.LabelFor(n => n.FirstName)
        @Html.TextBoxFor(n => n.FirstName, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(n => n.EventName)
        @Html.TextBoxFor(n => n.EventName, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(n => n.TimeofEvent)
        @Html.TextBoxFor(n => n.TimeofEvent, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(n => n.Location)
        @Html.TextBoxFor(n => n.Location, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(n => n.AdditionalNotes)
        @Html.TextBoxFor(n => n.AdditionalNotes, new { @class = "form-control" })
    </div>

    <div>
        <button type="submit" class="btn btn-primary" onclick="insertQuery">Save</button>
    </div>
</form>

}

CalendarApp/Views/MonthView/Index.cshtml
<!--model ienumerable myviewmodel-->
@using System.Linq;
@{

    ViewBag.Title = "Month";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 align="center">@Model.Month.ToString("MMMM")</h2>
<h2 align="center">@Model.Month.Year</h2>

<body>
    <table class="month-view" style="float: left">
        <tr>
            @foreach (DayOfWeek dayOfWeek in Enum.GetValues(typeof(DayOfWeek)))
            {
                <th>@dayOfWeek.ToString().Substring(0, 1)</th>
            }
        </tr>
        @foreach (var week in Model.Weeks)
        {
            <tr>
                @if (week[0].Date.DayOfWeek != DayOfWeek.Sunday)
                {
                    foreach (DayOfWeek dayOfWeek in Enum.GetValues(typeof(DayOfWeek)))
                    {
                        if (dayOfWeek < week[0].Date.DayOfWeek)
                        {
                            <td></td>
                        }
                    }
                }

                @foreach (var day in week)
                {
                    <td>
                        @day.Date.Day
                        <ul class="event-list">
                        @foreach (var newEvent in day.Events)
                        {
                            <li class="list-unstyled">
                                @Html.ActionLink((string) newEvent.EventName, "Single", new { id = newEvent.ID })
                            </li>
                        }
                        </ul>
                    </td>
                }

                @if (week.Count < 7 && week[week.Count - 1].Date.DayOfWeek != DayOfWeek.Saturday)
                {
                    foreach (DayOfWeek dayOfWeek in Enum.GetValues(typeof(DayOfWeek)))
                    {
                        if (dayOfWeek > week[week.Count - 1].Date.DayOfWeek)
                        {
                            <td></td>
                        }
                    }
                }
            </tr>

        }
    </table>

    <button class="btn btn-primary new-button" data-toggle="modal" data-target="#myModal">
        @Html.ActionLink("+", "New", "MonthView")
    </button>

</body>


<div id="myModal" class="modal fade " tabindex="-1" role="dialog">
    <div class="form-group">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                @using (Html.BeginForm("New", "MonthView"))
                {
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">New Event</h4>
                    </div>
                    <div class="modal-body">
                        <p>Name of event:</p> <input name="EventName" type="text">
                        <p> Date and Time: </p> <input name="TimeofEvent" type="datetime">
                        <p> Location: </p> <input name="Location" type="text">
                        <p>Additional notes:</p> <textarea name="AdditionalNotes"></textarea>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">
                            Save
                        </button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $('#myModal')
            function (e) {
                $(this)
                    .find('.btn.primary')
                    .attr('href', $(e.relatedTarget).data('href'));
            });
    </script>
}

CalendarApp/Views/MonthView/Single.cshtml
@model CalendarApp.Models.NewEvent
@{
    ViewBag.Title = "Single";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Event Info</h2>

<table class="table-hover" width="100%">

    &nbsp;
    &nbsp;
    &nbsp;
    <tr>
        <td> @Html.LabelFor(e => e.EventName)</td>
        <td> @Model.EventName.ToString()</td>
    </tr>

    <tr>
        <td> @Html.LabelFor(e => e.Location)</td>
        <td> @Model.Location.ToString()</td>
    </tr>

    <tr>
        <td> @Html.LabelFor(e => e.TimeofEvent)</td>
        <td> @Model.TimeofEvent.ToString()</td>
    </tr>

    <tr>
        <td> @Html.LabelFor(e => e.AdditionalNotes)</td>
        <td> @Model.AdditionalNotes.ToString()</td>
    </tr>
</table>

&nbsp;
&nbsp;
&nbsp;
<p>
    @Html.ActionLink("Back to Month", "Index", "MonthView", null, new { @class = "btn btn-primary" })
    @Html.ActionLink("Edit Event", "Edit", "MonthView", new { id = Model.ID }, new { @class = "btn" })

        <button class="btn btn-danger"
                data-href="@Url.Action("Delete",
                "MonthView",
                new { ID = Model.ID})"
                data-toggle="modal"
                data-target="#confirm-delete">
            Delete
    </button>
</p>

@section scripts
    {
    <script>
        $('confirm-delete').on('show.bs.modal', function (e) {
            $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));

            $('.debug-url').html('Delete URL: <strong>' + $(this).find('.btn-ok').attr('href') + '</strong>');
        });
    </script>
    }